INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE) values (0, 'admin', '$2a$12$MZylFGrGDAOsuLqSakerYeD25wueKDn0UhjleD2r9AzKbtF6L0aEK', 'ADMIN');
INSERT INTO USERS (ID, LOGIN, PASSWORD, ROLE) values (1, 'user', '$2a$12$nUpmtO.4xddxJO8ez.wLcOCPA0HZ9pVFPiqcZQBo.LZC2f9LqXjqe', 'USER');
INSERT INTO PROJECTS (name, parent, child) values ('project1', false, true );
INSERT INTO PROJECTS (name, parent, child) values ('subproject1',true, false);
INSERT INTO PROJECTS (name, parent, child) values ('subproject2', true, true);
INSERT INTO PROJECTS (name, parent, child) values ('subSubproject1', true, false);
INSERT INTO HIERARCHY_PROJECTS (id_parent, id_child) values (1, 2);
INSERT INTO HIERARCHY_PROJECTS (id_parent, id_child) values (1, 3);
INSERT INTO HIERARCHY_PROJECTS (id_parent, id_child) values (3, 4);
INSERT INTO TASKS (name, date_change, date_create, text, type, status) values ('name',  'date','date' ,'task1', 'ENGINEER', 'NEW');
INSERT INTO TASKS (name, date_change, date_create, text, type, status) values ('name',  'date','date' ,'task2','ENGINEER', 'NEW');
INSERT INTO TASKS (name, date_change, date_create, text, type, status) values ('name',  'date','date' ,'task3','ENGINEER', 'NEW');
INSERT INTO HIERARCHY_TASKS (id_project, id_task) values (1, 1);
INSERT INTO HIERARCHY_TASKS (id_project, id_task) values (2, 2);
INSERT INTO HIERARCHY_TASKS (id_project, id_task) values (3, 3);
INSERT INTO TASKS_TO_USERS (ID_TASK, ID_USER) values (1, 0);
INSERT INTO TASKS_TO_USERS (ID_TASK, ID_USER) values (2, 0);
INSERT INTO TASKS_TO_USERS (ID_TASK, ID_USER) values (3, 1);
commit;